#TODO
# Auto generate domain/directory/artifact/dbName from branch name
# Additional steps for non productional build e.g. db migrations/seeding
# Dockerized server [dynamic subdomain mapping] (https://stackoverflow.com/a/39058593)

# Builds and deploy to required server
name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Env'     
        required: true
        default: 'dev'
      branch_ref:
        description: 'Ref'     
        required: true
        default: 'dev'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - name: Declarations
        id: declare
        uses: actions/github-script@v4
        with:
          script: |
            const refInfo = context.ref.split('/')
            const domain= refInfo[2] + refInfo[3]? refInfo.split("-")[1]: ""
            core.setOutput('domain', domain)

      - name: Final step
        run: echo "Got domain ${{steps.declare.outputs.domain}}"

