
# Builds and deploy to required server
name: Deploy

on:
  workflow_dispatch:
    inputs:

      env:
        description: 'Env'     
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Installing core packages
        run: npm i

      - name: Checking linting issues
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.ref }}
          path: |
            dist

  deploy:
    environment: ${{ github.event.inputs.env }}
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Pull archive
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.ref }}
      
      - name: Setting env
        run: |
          echo "Deploying on ${{ github.event.inputs.env }} from branch ${{ github.ref }}"
          touch .env
          echo NODE_ENV= ${{ github.event.inputs.env }} >> .env

      - name: Terminate
        run: exit 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploying to S3 bucket
        run: aws s3 sync . s3://${{ secrets.AWS_FRONT_END_BUCKET }}/ --delete
