
# Builds and deploy to required server
name: Deploy

on:
  workflow_dispatch:
    inputs:

      env:
        description: 'Env'     
        required: true
        default: 'dev'
      branch_ref:
        description: 'Ref'     
        required: true
        default: 'dev'

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            whoami
            ls -al
