
# Builds and deploy to required server
name: Develop

# branch (master, hotfix, release, develop, feature/<domain>)
# jobs (hold, build, test, performance, staging, uat, production)
# github.sha

on:
  push:
    branches:
      - dev
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installation
        run: |
          npm i
          npm i -D

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: github.sha
          path: |
            dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Pull archive
        uses: actions/download-artifact@v2
        with:
          name: github.sha
      
      - name: Deploy
        run: |
          echo "Deploying."
          ls -a
