
name: Test CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      command:
        description: 'Command'     
        required: true
        default: 'build'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: exit 0

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: exit 0

  deploy:
    if: github.event.inputs.command == 'deploy' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: exit 0

